# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Current Research
    url: "/#research"
    weight: 20
  - name: Selected Work
    identifier: selected-work
    weight: 30
  - name: Overview
    parent: selected-work
    url: "#outputs"
    weight: 30
  - name: Transient Brokerage
    parent: selected-work
    url: "/transient-brokerage/"
    weight: 31
  - name: Teaching
    url: "/#teaching"
    weight: 40
#  - name: Talks
#    url: '#talks'
#    weight: 40
#  - name: Publications
#    url: '#featured'
#    weight: 50
#  - name: Contact
#    url: '#contact'
#    weight: 60
